

//
// This code was generated by a tool. Any changes made manually will be lost the next time this code is regenerated.
//
using System.Reflection;
using System.Runtime.InteropServices;

// IncreaseBuildVersion: False
// IncreaseRevisionVersion: False

// General Information about an assembly is controlled through the following set of attributes. 
[assembly: AssemblyVersion("0.2.0.8")]
[assembly: AssemblyFileVersion("0.2.0.8")]
[assembly: AssemblyCompany("Cloud17")]
[assembly: AssemblyCopyright("Copyright (c) Stepan Fryd 2012")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyConfiguration("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]