//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gaia.Portal.Framework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HttpStatusMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HttpStatusMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gaia.Portal.Framework.Resources.HttpStatusMessages", typeof(HttpStatusMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BadGateway.
        /// </summary>
        internal static string BadGateway {
            get {
                return ResourceManager.GetString("BadGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conflict.
        /// </summary>
        internal static string Conflict {
            get {
                return ResourceManager.GetString("Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpectationFailed.
        /// </summary>
        internal static string ExpectationFailed {
            get {
                return ResourceManager.GetString("ExpectationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden.
        /// </summary>
        internal static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GatewayTimeout.
        /// </summary>
        internal static string GatewayTimeout {
            get {
                return ResourceManager.GetString("GatewayTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gone.
        /// </summary>
        internal static string Gone {
            get {
                return ResourceManager.GetString("Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpVersionNotSupported.
        /// </summary>
        internal static string HttpVersionNotSupported {
            get {
                return ResourceManager.GetString("HttpVersionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InternalServerError.
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LengthRequired.
        /// </summary>
        internal static string LengthRequired {
            get {
                return ResourceManager.GetString("LengthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MethodNotAllowed.
        /// </summary>
        internal static string MethodNotAllowed {
            get {
                return ResourceManager.GetString("MethodNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotAcceptable.
        /// </summary>
        internal static string NotAcceptable {
            get {
                return ResourceManager.GetString("NotAcceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotFound.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotImplemented.
        /// </summary>
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentRequired.
        /// </summary>
        internal static string PaymentRequired {
            get {
                return ResourceManager.GetString("PaymentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreconditionFailed.
        /// </summary>
        internal static string PreconditionFailed {
            get {
                return ResourceManager.GetString("PreconditionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProxyAuthenticationRequired.
        /// </summary>
        internal static string ProxyAuthenticationRequired {
            get {
                return ResourceManager.GetString("ProxyAuthenticationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestedRangeNotSatisfiable.
        /// </summary>
        internal static string RequestedRangeNotSatisfiable {
            get {
                return ResourceManager.GetString("RequestedRangeNotSatisfiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestEntityTooLarge.
        /// </summary>
        internal static string RequestEntityTooLarge {
            get {
                return ResourceManager.GetString("RequestEntityTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestTimeout.
        /// </summary>
        internal static string RequestTimeout {
            get {
                return ResourceManager.GetString("RequestTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestUriTooLong.
        /// </summary>
        internal static string RequestUriTooLong {
            get {
                return ResourceManager.GetString("RequestUriTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceUnavailable.
        /// </summary>
        internal static string ServiceUnavailable {
            get {
                return ResourceManager.GetString("ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnsupportedMediaType.
        /// </summary>
        internal static string UnsupportedMediaType {
            get {
                return ResourceManager.GetString("UnsupportedMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpgradeRequired.
        /// </summary>
        internal static string UpgradeRequired {
            get {
                return ResourceManager.GetString("UpgradeRequired", resourceCulture);
            }
        }
    }
}
